version: '3.8'

services:
  web:
    image: php:8.0-apache
    ports:
      - "2000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data